//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Accelerator
{
	/// <summary>
	/// Represents a content item of type <see cref="Image"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Image : IContentItemFieldsSource, IMediaSchema
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Accelerator.Image";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// ImageFile.
		/// </summary>
		public ContentItemAsset ImageFile { get; set; }


        /// <summary>
        /// ImageAltText.
        /// </summary>
        public string ImageAlternateText { get; set; }


        /// <summary>
        /// MediaTitle.
        /// </summary>
        public string MediaTitle { get; set; }


		/// <summary>
		/// MediaDescription.
		/// </summary>
		public string MediaDescription { get; set; }


		/// <summary>
		/// MediaTags.
		/// </summary>
		public IEnumerable<TagReference> MediaTags { get; set; }
	}
}