//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;
using CMS.MediaLibrary;

namespace Accelerator
{
	/// <summary>
	/// Represents a page of type <see cref="Article"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Article : IWebPageFieldsSource, ISeoPageSchema
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Accelerator.Article";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// ArticleTitle.
		/// </summary>
		public string ArticleTitle { get; set; }


		/// <summary>
		/// ArticleSubtitle.
		/// </summary>
		public string ArticleSubtitle { get; set; }


		/// <summary>
		/// ArticleDescription.
		/// </summary>
		public string ArticleDescription { get; set; }


		/// <summary>
		/// ResourceDate.
		/// </summary>
		public DateTime ResourceDate { get; set; }


		/// <summary>
		/// ArticleBody.
		/// </summary>
		public string ArticleBody { get; set; }


		/// <summary>
		/// AlertImageContentItem.
		/// </summary>
		public IEnumerable<Image> ArticleImageContentItem { get; set; }


		/// <summary>
		/// ResourceIsFeatured.
		/// </summary>
		public bool ResourceIsFeatured { get; set; }


		/// <summary>
		/// ArticleDisclaimer.
		/// </summary>
		public string ArticleDisclaimer { get; set; }


		/// <summary>
		/// ArticleRelated.
		/// </summary>
		public IEnumerable<WebPageRelatedItem> ArticleRelated { get; set; }


		/// <summary>
		/// ArticleTags.
		/// </summary>
		public IEnumerable<TagReference> ArticleTags { get; set; }


		/// <summary>
		/// SEOPageTitle.
		/// </summary>
		public string SEOPageTitle { get; set; }


		/// <summary>
		/// SEOPageDescription.
		/// </summary>
		public string SEOPageDescription { get; set; }


		/// <summary>
		/// SEOPageDate.
		/// </summary>
		public DateTime SEOPageDate { get; set; }


		/// <summary>
		/// SEOPageKeywords.
		/// </summary>
		public string SEOPageKeywords { get; set; }


		/// <summary>
		/// SEOPageNoFollow.
		/// </summary>
		public bool SEOPageNoFollow { get; set; }


		/// <summary>
		/// SEOPageNoIndex.
		/// </summary>
		public bool SEOPageNoIndex { get; set; }


		/// <summary>
		/// SEOPageScript.
		/// </summary>
		public string SEOPageScript { get; set; }


		/// <summary>
		/// SEOPageSocialMediaImage.
		/// </summary>
		public string SEOPageSocialMediaImage { get; set; }


		/// <summary>
		/// SEOPageSocialMediaImageAltText.
		/// </summary>
		public string SEOPageSocialMediaImageAltText { get; set; }


		/// <summary>
		/// SEOPageSchemaOrgEnabled.
		/// </summary>
		public bool SEOPageSchemaOrgEnabled { get; set; }


		/// <summary>
		/// SEOHidePageFromSite.
		/// </summary>
		public bool SEOHidePageFromSite { get; set; }
	}
}
