//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Accelerator
{
	/// <summary>
	/// Represents a content item of type <see cref="Media"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Media : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Accelerator.Media";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Asset.
		/// </summary>
		public ContentItemAsset Asset { get; set; }


		/// <summary>
		/// AssetText.
		/// </summary>
		public string AssetText { get; set; }


		/// <summary>
		/// AssetDescription.
		/// </summary>
		public string AssetDescription { get; set; }


		/// <summary>
		/// AssetType.
		/// </summary>
		public string AssetType { get; set; }
	}
}